name: Build and Upload

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyyaml jsonschema pyqt5

    - name: Build project
      run: pyinstaller --onefile --noconsole file_converter.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/file_converter.exe

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pyinstaller pyyaml jsonschema pyqt5
      - name: Build project
        run: pyinstaller --onefile --noconsole file_converter.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist/file_converter.exe

