name: Build and Upload

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install pyinstaller pyyaml jsonschema
      - name: Build project
        run: pyinstaller --onefile --noconsole file_converter.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist/file_converter.exe
